### PR TITLE
Refactor default handling

### PR DESCRIPTION
**Pull request by tiljanssen**
- make default presets relative to now() (solves #66)
- add this month only for default presets (solves #65)
- do not include default/custom presets that have a "negative" range

### CODE REVIEW

**Comment by tiljanssen** [comment]
@tyvdh Can you merge this soon, because I really want to use the newer version, but that won't do with this extra entry in the presets

**Comment by kalepail** [comment]
@tiljanssen It's not working for me atm. Did you build and test at all?

**Comment by kalepail** [comment]
screen shot 2016-10-18 at 12 04 04 pm

**Comment by tiljanssen** [comment]
I have troubles getting your build scripts up and running so I tested it locally in my own code. Let me check whether I have committed al the changes I made.

**Pull request closed without merging**
