### PR TITLE
Display formats & i18n

### LINKED ISSUE #2: Internacionalization
Just as an enhancement, please provide the ability to get translations, maybe via external files

### PR DESCRIPTION
**Pull request by SleeplessByte**
# Display formats and localization

Fixes #2 except for the presets. I will tackle that in a different branch, because the presets should be complete rewritten.

It now supports ANY display format for the date, a transform function for the day, month and year displays, a format for the month and year switchers and automagically uses moment's locale.
## Locale

Set `moment.locale( ... )` to instantly localize the entire picker for a locale, except for the display date. Follow instructions on [momentjs.com](http://momentjs.com) how to include a locale file.
## Display format options
- Use `display_format = moment_format` for display dates. 
  - Accepts any format, such as `D [x]  MMMM [x] YY`.
  - Default is `MMMM D, YYYY`
  - Consider changing default to the localized variant `LL`
- Use `display_month_format = moment_format` for displayed month names (switcher).
  - Accepts `MMMM` and `MM`
  - Default is `MMMM`
- Use `display_year_format = moment_format` for displayed year names (switcher). 
  - Accepts `YYYY` and `YY`
  - Default is `YYYY`

The date parser that accepts `now`, `stringToDate` etc. now also parses using the set `display_format`.
## Transformation functions

Right before a day name, month name or year number is displayed in the switchers or the table header, it is ran through a tranformation function
- Use `transform_day = function(d){ return d; }` to transform the day display right before it's displayed. 
  - Defaults to a function that trims the string to a single character
  - No trimming (2 characters) actually looks great. 
  - Use `moment.weekDaysMin()` to match the value with the day.
  - Consider accepting an array of week days etc. to display instead
- Use `transform_month` for the month switcher
- Use `transform_year` for the year switcher

The month/year values of the switchers are stored into data variables (because with the transform functions, you could irreversibly transform the string).

### CODE REVIEW

**Comment by kalepail** [comment]
@SleeplessByte Made a number of changes due to other issues and requests. If you could confirm this branch is still working I'll take a look and likely merge. Thanks for the PR!!

**Comment by SleeplessByte** [comment]
I'll rebase it :)

**Comment by SleeplessByte** [comment]
I guess it was still working?

**Comment by kalepail** [comment]
Somewhat. I tweaked it a lot and took out the function actions.. but the idea as a whole was great!

**Pull request merged**
